spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?currentSchema=${DB_SCHEMA}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA}
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    default-schema: ${DB_SCHEMA}
  banner:
    location: banner

minio:
  url: ${MINIO_URL}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket:
    name: vpn

vpn:
  scripts:
    create: ${VPN_CREATE_SCRIPT}
    delete: ${VPN_DELETE_SCRIPT}
  output:
    dir: ${VPN_OUTPUT_DIR}

student:
  datasource:
    url: jdbc:postgresql://${STUDENT_DB_HOST}:${STUDENT_DB_PORT}/
    username: ${STUDENT_DB_USERNAME}
    password: ${STUDENT_DB_PASSWORD}